version: '3'

services:
  php74:
    build:
      context: .
    volumes:
      - ../:/var/www/html/
    ports:
      - ${WEB_PORT}:80
      - ${WEB_SSL_PORT}:443
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DBPASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
volumes:
  mysql_data: